return {
  -- disable trouble
  { "rcarriga/nvim-notify", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "fgheng/winbar.nvim", enabled = false },
  -- { "akinsho/bufferline.nvim", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "sphamba/smear-cursor.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "shellRaining/hlchunk.nvim", enabled = false },
  { "ibhagwan/fzf-lua", enabled = false },
  { "goolord/alpha-nvim", enabled = false },
  { "nvim-tree/nvim-tree.lua", enabled = false },
  { "debugloop/telescope-undo.nvim", enabled = false },
  { "Bekaboo/dropbar.nvim", enabled = false },
  -- { "saghen/blink.cmp", enabled = false },
  -- { "sphamba/smear-cursor.nvim", enabled = false },
  { "huggingface/llm.nvim", enabled = false },
  { "karb94/neoscroll.nvim", enabled = false },
  -- { "folke/snacks.nvim", enabled = false },
  -- { "kevinhwang91/nvim-ufo", enable = false },
  -- { "karb94/neoscroll.nvim", enable = false },
}
