theme="gruvbox"
[editor]
line-number = "relative"
mouse = true
cursorline=true
bufferline="multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"0"="goto_line_start"
"$"="goto_line_end"
