#!/usr/bin/env sh
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# .. more yabai startup stuff
yabai -m config external_bar all:35:0
yabai -m config window_placement second_child
yabai -m config layout bsp
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off
yabai -m config window_zoom_persist off
yabai -m config window_opacity off
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config menubar_opacity 0.0
# yabai -m config window_opacity_duration 0.2
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 0.95
# yabai -m config window_animation_duration 0.5
# yabai -m config auto_padding on
# yabai -m config window_topmost off
# yabai -m config window_shadow float

yabai -m config top_padding 3
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 8
# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Wechat" app="^微信$" title="朋友圈|相册-墨先生" manage=off
yabai -m rule --add label="matlab" app="^MATLAB$" title="MATLAB R2023a - academic use" manage=off
yabai -m rule --add label="redbook" app="^discover$" title="小红书" manage=off
# yabai -m rule --add label="Downie" app="^Downie$" title="Downie" manage=off
yabai -m rule --add label="Shadowrocket" app="^Shadowrocket$" title="^Shadowrocket$" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
# yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="(QQ|Wechat)" space=^2
yabai -m rule --add app="Arc" space=^1
yabai -m rule --add app="Kitty" space=^3

otherApp='^(IINA|Tencent Lemon|Clash Verge|360安全云盘|arknights|音乐|MotionPro| discover |ChatGPT|PlayCover|访达|Calendar|日历|地图|System Preferences|朋友圈|小程序|Downie 4|Shadowrocket| |照片|Epson iProjection|系统设置|1Password 7|Android Studio|印象笔记|MATLAB|CrossOver)$'
yabai -m rule --add app="${otherApp}" manage=off

echo "yabai configuration loaded.."
