#!/usr/bin/env sh
# for this to work you must configure sudo such that
# it will be able to run the command without password

/opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo /opt/homebrew/bin/yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# .. more yabai startup stuff
/opt/homebrew/bin/yabai -m config external_bar all:35:0
/opt/homebrew/bin/yabai -m config mouse_follows_focus on
/opt/homebrew/bin/yabai -m config focus_follows_mouse off
/opt/homebrew/bin/yabai -m config window_zoom_persist off
/opt/homebrew/bin/yabai -m config window_placement second_child
# /opt/homebrew/bin/yabai -m config window_topmost off
# /opt/homebrew/bin/yabai -m config window_shadow float
/opt/homebrew/bin/yabai -m config window_opacity off
# /opt/homebrew/bin/yabai -m config window_opacity_duration 0.2
#/opt/homebrew/bin/yabai -m config active_window_opacity 1.0
#/opt/homebrew/bin/yabai -m config normal_window_opacity 0.95
# /opt/homebrew/bin/yabai -m config window_animation_duration 0.5
/opt/homebrew/bin/yabai -m config split_ratio 0.50
/opt/homebrew/bin/yabai -m config auto_balance off
# /opt/homebrew/bin/yabai -m config auto_padding on
/opt/homebrew/bin/yabai -m config mouse_modifier fn
/opt/homebrew/bin/yabai -m config mouse_action1 move
/opt/homebrew/bin/yabai -m config mouse_action2 resize
/opt/homebrew/bin/yabai -m config mouse_drop_action swap

/opt/homebrew/bin/yabai -m config top_padding 10
/opt/homebrew/bin/yabai -m config bottom_padding 10
/opt/homebrew/bin/yabai -m config left_padding 10
/opt/homebrew/bin/yabai -m config right_padding 10
/opt/homebrew/bin/yabai -m config window_gap 10
# Exclude problematic apps from being managed:
/opt/homebrew/bin/yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store|Steam|Alfred|Activity Monitor)$" manage=off
/opt/homebrew/bin/yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
/opt/homebrew/bin/yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
/opt/homebrew/bin/yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
/opt/homebrew/bin/yabai -m rule --add label="Wechat" app="^微信$" title="朋友圈" manage=off
/opt/homebrew/bin/yabai -m rule --add label="Shadowrocket" app="^Shadowrocket$" title="Shadowrocket" manage=off
/opt/homebrew/bin/yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^System Preferences$" manage=off
/opt/homebrew/bin/yabai -m config layout bsp

otherApp='^(IINA|访达|Calendar|日历|地图|System Preferences|朋友圈|小程序|Shadowrocket|Epson iProjection|系统设置|1Password 7|Android Studio|印象笔记)$'
/opt/homebrew/bin/yabai -m rule --add app="${otherApp}" manage=off

echo "yabai configuration loaded.."
