require("items.widgets.battery")
require("items.widgets.qq")
require("items.widgets.wechat")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.tempture")
require("items.widgets.cpu")
