require("items.widgets.battery")
-- require("items.widgets.switch")
require("items.widgets.qq")
require("items.widgets.wechat")
require("items.widgets.volume")
require("items.widgets.wifi")
require("items.widgets.cpu_and_temp")
-- require("items.widgets.temperature")
-- require("items.widgets.cpu")
