#!/bin/bash

options=(
  style=round
  # style=square
  width=5.0
  hidpi=on
  # active_color=0xff8a866e
  active_color=0xff81969e
  inactive_color=0xff414550
  # background_color=0xff81969e
  blacklist="sketchybar,Safari,iPhone Mirroring,Steam Helper"
  blur_radius=1
)

borders "${options[@]}"
